name: Superlists Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      HOST_USER: ${{ secrets.HOST_USER }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.16'
        
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'
        
    - name: Install gecko-driver
      uses: browser-actions/setup-geckodriver@latest
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python manage.py migrate
        python manage.py test
